#!/bin/bash
#Menu
clear
echo -e ""
echo -e "===============================-Menu-==============================="
echo -e "* menu         : Menampilkan Daftar Perintah Utama"
echo -e ""
echo -e "========================-Menu SSH & OpenVPN-========================"
echo -e "* usernew      : Membuat Akun SSH & OpenVPN"
echo -e "* trial        : Generate Akun Trial SSH & OpenVPN"
echo -e "* renew        : Memperpanjang Masa Aktif Akun SSH & OpenVPN"
echo -e "* hapus        : Menghapus Akun SSH & OpenVPN"
echo -e "* cek          : Cek User Login"
echo -e "* member       : Daftar Member SSH & OpenVPN"
echo -e "* delete       : Delete User Expired"
echo -e "* autokill	: Mengatur AutoKill"
echo -e "* ceklim	: Melihat User Yang Melakukan Multi Login"
echo -e "* restart      : Restart Service Dropbear, Webmin, Squid3,"
echo -e "                 OpenVPN dan SSH"
echo -e ""
echo -e "===========================-Menu Wireguard-========================="
echo -e "* wgadd        : Generate Akun Wireguard"
echo -e "* wdel         : Menghapus Akun Wireguard"
echo -e "* wg show      : Cek User Interface Wireguard"
echo -e ""
echo -e "==========================-Menu L2TP/IPSEC-========================="
echo -e "* addvpn       : Membuat Akun L2TP/IPSEC"
echo -e "* delvpn       : Menghapus Akun L2TP/IPSEC"
echo -e ""
echo -e "=============================-Menu SSR-============================="
echo -e "* ssr          : Menampilkan Menu Utama SSR"
echo -e "* ssradd	: Membuat Akun SSR"
echo -e "* ssrdel	: Menghapus Akun SSR"
echo -e ""
echo -e "=============================-Menu V2ray============================"
echo -e "* V2ray	: Menampilkan Pilihan Utama V2ray"
echo -e ""
echo -e "=============================-Menu SYSTEM-=========================="
echo -e "* ram          : Cek Penggunaan Ram VPS"
echo -e "* reboot       : Reboot VPS"
echo -e "* speedtest    : Speedtest VPS"
echo -e "* info         : Menampilkan Informasi Sistem"
echo -e "* about        : Info Script Auto Install"
echo -e "* exit         : Keluar Dari Putty/Connecbot/JuiceSSH"
echo -e ""
echo -e "====================================================================="
echo -e ""
